replicaCount: 2

image:
  repository: rogerzhuang/genai-bproc
  tag: latest

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

service:
  type: NodePort
  port: 80
  targetPort: 5000

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50