apiVersion: v1
kind: Secret
metadata:
  name: openai-api-keys
type: Opaque
stringData:
  api-keys: {{ .Values.openaiApiKeys | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  access-key: {{ index .Values "minio" "auth" "rootUser" | quote }}
  secret-key: {{ index .Values "minio" "auth" "rootPassword" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  access-key: {{ index .Values "rabbitmq" "auth" "username" | quote }}
  secret-key: {{ index .Values "rabbitmq" "auth" "password" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: load-definition
type: Opaque
stringData:
  load_definition.json: |
    {
      "rabbit_version": {{ .Values.rabbitmqLoadDefinition.rabbitVersion | quote }},
      "users": [
        {
          "name": {{ index .Values "rabbitmqLoadDefinition" "users" 0 "name" | quote }},
          "password": {{ index .Values "rabbitmqLoadDefinition" "users" 0 "password" | quote }},
          "tags": {{ index .Values "rabbitmqLoadDefinition" "users" 0 "tags" | quote }}
        }
      ],
      "vhosts": [
        {
          "name": {{ index .Values "rabbitmqLoadDefinition" "vhosts" 0 "name" | quote }}
        }
      ],
      "permissions": [
        {
          "user": {{ index .Values "rabbitmqLoadDefinition" "permissions" 0 "user" | quote }},
          "vhost": {{ index .Values "rabbitmqLoadDefinition" "permissions" 0 "vhost" | quote }},
          "configure": {{ index .Values "rabbitmqLoadDefinition" "permissions" 0 "configure" | quote }},
          "write": {{ index .Values "rabbitmqLoadDefinition" "permissions" 0 "write" | quote }},
          "read": {{ index .Values "rabbitmqLoadDefinition" "permissions" 0 "read" | quote }}
        }
      ],
      "policies": [
        {
          "vhost": {{ index .Values "rabbitmqLoadDefinition" "policies" 0 "vhost" | quote }},
          "name": {{ index .Values "rabbitmqLoadDefinition" "policies" 0 "name" | quote }},
          "pattern": {{ index .Values "rabbitmqLoadDefinition" "policies" 0 "pattern" | quote }},
          "apply-to": {{ index .Values "rabbitmqLoadDefinition" "policies" 0 "applyTo" | quote }},
          "definition": {
            "ha-mode": {{ index .Values "rabbitmqLoadDefinition" "policies" 0 "definition" "ha-mode" | quote }},
            "ha-sync-mode": {{ index .Values "rabbitmqLoadDefinition" "policies" 0 "definition" "ha-sync-mode" | quote }}
          }
        }
      ]
    }