---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bproc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bproc
  template:
    metadata:
      labels:
        app: bproc
    spec:
      containers:
        - name: bproc
          image: rogerzhuang/genai-bproc:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 5000
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: access-key
            - name: RABBITMQ_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: secret-key
            - name: MINIO_URL
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
            - name: REDIS_CLUSTER
              value: "redis-service"
            - name: OPENAI_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: openai-api-keys
                  key: api-keys
---
apiVersion: v1
kind: Service
metadata:
  name: bproc-service
spec:
  selector:
    app: bproc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: rogerzhuang/genai-bproc:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          command:
            [
              "celery",
              "-A",
              "app_batch.celery",
              "worker",
              "--loglevel=info",
              "-P",
              "eventlet",
            ]
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: access-key
            - name: RABBITMQ_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: secret-key
            - name: MINIO_URL
              value: "minio-service:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
            - name: REDIS_CLUSTER
              value: "redis-service"
            - name: OPENAI_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: openai-api-keys
                  key: api-keys
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
        - name: redis-commander
          image: rediscommander/redis-commander:latest
          env:
            - name: REDIS_HOSTS
              value: "instance1:redis-service-0.redis-service-headless.default.svc.cluster.local:6379,instance2:redis-service-1.redis-service-headless.default.svc.cluster.local:6379,instance3:redis-service-2.redis-service-headless.default.svc.cluster.local:6379,instance4:redis-service-3.redis-service-headless.default.svc.cluster.local:6379,instance5:redis-service-4.redis-service-headless.default.svc.cluster.local:6379,instance6:redis-service-5.redis-service-headless.default.svc.cluster.local:6379"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
spec:
  selector:
    app: redis-commander
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bproc-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bproc
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
