mode: distributed
replicas: 4

auth:
  rootUser: "minio"
  rootPassword: "minio123"

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 1Gi

service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

