replicaCount: 3

auth:
  username: admin
  password: rabbitmq123

persistence:
  enabled: true
  # accessModes:
  #   - ReadWriteOnce
  size: 1Gi

service:
  type: ClusterIP

rabbitmq:
  extraConfiguration: |
    load_definitions = /app/load_definition.json

extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "admin",
            "password": "rabbitmq123",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "bproc"
          }
        ],
        "permissions": [
          {
            "user": "admin",
            "vhost": "bproc",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "policies": [
          {
            "vhost": "bproc",
            "name": "ha-all",
            "pattern": ".*",
            "apply-to": "all",
            "definition": {
              "ha-mode": "all",
              "ha-sync-mode": "automatic"
            }
          }
        ]
      }

loadDefinition:
  enabled: true
  existingSecret: load-definition
