# redis-values.yaml
architecture: replication

auth:
  enabled: false

master:
  count: 3
  persistence:
    enabled: true
    size: 1Gi
  extraEnvVars:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
  extraEnvVars:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"

sentinel:
  enabled: true
  extraEnvVars:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"

service:
  type: ClusterIP

externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    port: 6379

networkPolicy:
  enabled: false

metrics:
  enabled: true

# Override the generated fullname to use a specific service name
fullnameOverride: "redis-service"

# Ensure no password is generated or used
usePassword: false
usePasswordFile: false
existingSecret: ""
redisPassword: ""
