# redis-values.yaml
architecture: replication

auth:
  enabled: false

master:
  count: 3
  persistence:
    enabled: true
    size: 1Gi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi

sentinel:
  enabled: true

service:
  type: ClusterIP

externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    port: 6379

metrics:
  enabled: true

# Override the generated fullname to use a specific service name
fullnameOverride: "redis-service"

# Ensure no password is generated or used
usePassword: false
usePasswordFile: false
existingSecret: ""
redisPassword: ""
